# Basic colors
foreground              #e5e1e9
background              #131318
selection_foreground    #e4dff9
selection_background    #474459

# Cursor colors
cursor                  #c5c0ff
cursor_text_color       #2e2960

# URL underline color when hovering with mouse
url_color               #ebb8cf

# Kitty window border colors
active_border_color     #c5c0ff
inactive_border_color   #47464f
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #e4dfff
active_tab_background   #444078
inactive_tab_foreground #c8c5d0
inactive_tab_background #201f25
tab_bar_background      #131318

# Colors for marks
mark1_foreground #2e2960
mark1_background #c5c0ff
mark2_foreground #302e41
mark2_background #c8c4dc
mark3_foreground #482537
mark3_background #ebb8cf

# The 16 terminal colors
# black
color0 #47464f
color8 #928f99

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #c5c0ff
color10 #e4dfff

# yellow
color3  #ebb8cf
color11 #ffd8e8

# blue
color4  #c8c4dc
color12 #e4dff9

# magenta
color5  #444078
color13 #5c5891

# cyan
color6  #474459
color14 #613b4e

# white
color7  #c8c5d0
color15 #e5e1e9
